// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/3/2568 21:35:03
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/User/Documents/GitHub/interactive_website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/Documents/GitHub/interactive_website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/Documents/GitHub/interactive_website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/Documents/GitHub/interactive_website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/Documents/GitHub/interactive_website/plugins/**/*.{js,ts,mjs}","C:/Users/User/Documents/GitHub/interactive_website/composables/**/*.{js,ts,mjs}","C:/Users/User/Documents/GitHub/interactive_website/utils/**/*.{js,ts,mjs}","C:/Users/User/Documents/GitHub/interactive_website/pages/index.vue","C:/Users/User/Documents/GitHub/interactive_website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/Documents/GitHub/interactive_website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/Documents/GitHub/interactive_website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;