// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/1/2025, 10:48:36 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/jaja/Desktop/git-local/interactive_website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jaja/Desktop/git-local/interactive_website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jaja/Desktop/git-local/interactive_website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jaja/Desktop/git-local/interactive_website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jaja/Desktop/git-local/interactive_website/plugins/**/*.{js,ts,mjs}","/Users/jaja/Desktop/git-local/interactive_website/composables/**/*.{js,ts,mjs}","/Users/jaja/Desktop/git-local/interactive_website/utils/**/*.{js,ts,mjs}","/Users/jaja/Desktop/git-local/interactive_website/pages/index.vue","/Users/jaja/Desktop/git-local/interactive_website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jaja/Desktop/git-local/interactive_website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jaja/Desktop/git-local/interactive_website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;