// Generated by @hypernym/nuxt-gsap
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
export declare const useGsap: typeof gsap;
export declare const useScrollTrigger: typeof ScrollTrigger;